modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "GNU AGPL 3.0"

[[mods]]
modId = "eepy_critters"
version = "${version}"
displayName = "Eepy Critters"
authors = "tired9494"
description = '''

'''
#logoFile = ""

[[dependencies.eepy_critters]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.eepy_critters]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.8,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.eepy_critters]]
modId = "architectury"
type = "required"
versionRange = "[17.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "eepy_critters.mixins.json"
